FROM python:3.10.8
ENV PYTHONUNBUFFERED 1
WORKDIR /server
COPY requirements.txt /server/requirements.txt
RUN pip install -r requirements.txt
COPY . /server

CMD python manage.py runserver 0.0.0.0:8000